(bug) Address will now account for and catch Geolocation API when use…
scooby-gang-12/PickUpPulse pull request #10
Opened 2023-10-26 01:24 UTC by djsong15

## Overview

**Issue Type**

-[x] Bug
-[ ] Feature
-[ ] Tech Debt

**Description**
Fixed bug where address will default to default location (10 Van Ness Ave, SF); will now check Geolocation API and geocode the returned lat/lng into a formatted address using Google Map's Geocode library

**Ticket/Card Name**

**Trello link - (https://trello.com/c/F4taiO6o)**
	
**Steps to Reproduce Bug**

1. Share location in browser
2. Sign in
3. Confirm incorrect address

2023-10-26 02:50 UTC, tristanSW requested changes
The bug fix mentioned worked as intended, however a bug was found. Waiting to merge until it's fixed as well. 
(The bug in question: If user is sharing their location, but manually enters a location, the map doesn't update, while the text does update but only for a small window of time; previous behavior: map doesn't update, but text does update)

2023-10-27 00:52 UTC, djsong15 commented
Bug fixed - map should now update with user-set location

2023-10-27 01:03 UTC, tristanSW approved these changes

2023-10-27 01:04 UTC, tristanSW commented
everything seems to work as expected!

2023-10-27 01:06 UTC, merged